# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/sm8350-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter r9q,$(TARGET_DEVICE)),)

endif
